const PDF_TEMPLATES = {
  professional: (title, content, iconBase64, metadata = {}) => `
    <html>
      <head>
        <style>
          body { font-family: 'Helvetica', sans-serif; padding: 40px; color: #333; line-height: 1.6; }
          .header { display: flex; align-items: center; border-bottom: 2px solid #4F46E5; padding-bottom: 20px; margin-bottom: 30px; }
          .logo { width: 50px; height: 50px; margin-right: 20px; }
          .title-area { flex-grow: 1; }
          h1 { margin: 0; color: #1F2937; font-size: 24px; }
          .metadata { font-size: 12px; color: #6B7280; margin-top: 5px; }
          .content { font-size: 14px; }
          table { width: 100%; border-collapse: collapse; margin: 20px 0; }
          th { background: #F3F4F6; text-align: left; padding: 10px; border: 1px solid #E5E7EB; }
          td { padding: 10px; border: 1px solid #E5E7EB; }
          blockquote { border-left: 4px solid #4F46E5; padding-left: 15px; font-style: italic; color: #4B5563; }
          code { background: #F3F4F6; padding: 2px 4px; border-radius: 4px; font-family: monospace; }
        </style>
      </head>
      <body>
        <div class="header">
          ${iconBase64 ? `<img src="${iconBase64}" class="logo" />` : ''}
          <div class="title-area">
            <h1>${title}</h1>
            <div class="metadata">
              ${metadata.author ? `<span>Author: ${metadata.author}</span> | ` : ''}
              <span>Generated by Comet-AI on ${new Date().toLocaleDateString()}</span>
            </div>
          </div>
        </div>
        <div class="content">${content}</div>
      </body>
    </html>
  `
};

function parseMarkdownTables(content) {
  const tableRegex = /\|(.+)\|\n\|[-:\s|]+\|\n((?:\|.+\|\n?)+)/g;
  return content.replace(tableRegex, (match, headerRow, bodyRows) => {
    const headers = headerRow.split('|').map(h => h.trim()).filter(h => h);
    const rows = bodyRows.trim().split('\n').map(row =>
      row.split('|').map(cell => cell.trim()).filter(c => c)
    );

    let html = '<div class="table-wrapper"><table><thead><tr>';
    headers.forEach(h => { html += `<th>${h}</th>`; });
    html += '</tr></thead><tbody>';
    rows.forEach(row => {
      html += '<tr>';
      row.forEach(cell => { html += `<td>${cell}</td>`; });
      html += '</tr>';
    });
    html += '</tbody></table></div>';
    return html;
  });
}

function parseMarkdownToHTML(content) {
  let html = content;
  html = html.replace(/^### (.+)$/gm, '<h3>$1</h3>');
  html = html.replace(/^## (.+)$/gm, '<h2>$1</h2>');
  html = html.replace(/^# (.+)$/gm, '<h1>$1</h1>');
  html = html.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
  html = html.replace(/\*(.+?)\*/g, '<em>$1</em>');
  html = html.replace(/`([^`]+)`/g, '<code>$1</code>');
  html = html.replace(/^> (.+)$/gm, '<blockquote>$1</blockquote>');
  html = html.replace(/^---$/gm, '<hr/>');
  return html;
}

function generateCometPDFTemplate(title, content, iconBase64, templateName = 'professional', metadata = {}) {
  const isFullHTML = /<html/i.test(content);
  if (isFullHTML) return content;

  let cleanContent = content
    .replace(/\[WATERMARK:\s*([^\]]+)\]/gi, (_, w) => { metadata.watermark = w; return ''; })
    .replace(/\[TEMPLATE:\s*([^\]]+)\]/gi, (_, t) => { templateName = t.toLowerCase(); return ''; });

  cleanContent = parseMarkdownTables(cleanContent);
  cleanContent = parseMarkdownToHTML(cleanContent);

  const template = PDF_TEMPLATES[templateName] || PDF_TEMPLATES.professional;
  return template(title, cleanContent, iconBase64, metadata);
}

module.exports = {
  generateCometPDFTemplate,
  parseMarkdownTables,
  parseMarkdownToHTML
};
